// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20260306171957_Image migration")]
    partial class Imagemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b709c0ce-14d1-4cfd-a395-939870baa4b7"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("0657e12b-df8c-4585-bc9b-3e73bd87641c"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("81c0af7a-71a0-4465-b3b8-f5c594d527e9"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a826c3b6-73e3-42ec-953b-89d846390445"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("890db9d2-d136-44fc-9d8a-0cbfbdf837f5"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("ed11cec3-239a-46ca-a3f7-d7ed254eb93e"),
                            Code = "WKO",
                            Name = "Waikato",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("13f6df00-5176-4f16-84c6-16bb68a64732"),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("ebef9e55-bab4-4cb7-8830-c1163cc1fda1"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("e5727df3-dd72-48ce-a1e3-43a8d0fb78d6"),
                            Code = "HKB",
                            Name = "Hawke's Bay",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("4d864403-cd39-41ea-9de0-2722be1d2889"),
                            Code = "TKI",
                            Name = "Taranaki",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("7e57aa5e-0e80-4bb7-8b68-8c2717bc1ea7"),
                            Code = "MWT",
                            Name = "Manawatū-Whanganui",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("6e9663ef-18ec-4e35-afda-2402ee6475aa"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("cf803131-4c4e-4611-aebc-2969786ca2fe"),
                            Code = "TSM",
                            Name = "Tasman",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("0ba74158-9b74-425d-aa08-6697129820d2"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("39b78159-3b00-4605-bd72-37cdd5b40a1f"),
                            Code = "MBH",
                            Name = "Marlborough",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("ba555ee1-d31b-4561-abb7-de08b74985ea"),
                            Code = "WTC",
                            Name = "West Coast",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("65abc285-2e72-45ac-8aa7-1166b069ed34"),
                            Code = "CAN",
                            Name = "Canterbury",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("4ce06d01-c392-46c7-b73e-9d677659cfa2"),
                            Code = "OTA",
                            Name = "Otago",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        },
                        new
                        {
                            Id = new Guid("e7975595-fe45-4cd4-843b-fd955bbe5503"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageUrl = "https://picsum.photos/200/200"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
